/**
 * Export Utility — PDF Generation. Generates a report suitable for documentation or stakeholder review. Design Principle: Transparent reasoning — every decision documented.
 */
import jsPDF from 'jspdf';
import type { SimulationResult, FlagDecision } from '@jikken/shared';

export function exportToPDF(params: {
  title: string;
  meta: SimulationResult;
  summary: SimulationResult['summary'];
  decisions: FlagDecision[];
}): void {
  const { title, meta, summary, decisions } = params;
  const doc = new jsPDF();
  doc.setFontSize(18);
  doc.text(title, 14, 20);
  doc.setFontSize(12);
  doc.text(`Flag: ${meta.flag_id}`, 14, 30);
  doc.text(`Simulation ID: ${meta.simulation_id}`, 14, 36);
  doc.text(`Evaluated: ${meta.evaluated_at}`, 14, 42);
  doc.text(`Latency: ${meta.total_latency_ms}ms`, 14, 48);
  doc.setFontSize(14);
  doc.text('Summary', 14, 60);
  doc.setFontSize(11);
  doc.text(
    `${summary.passed} Received  |  ${summary.conflicted} Excluded  |  ${summary.warned} Partial  |  ${summary.total} Total`,
    14, 67
  );
  let yPos = 80;
  doc.setFontSize(14);
  doc.text('Decision Trace', 14, yPos);
  yPos += 10;
  doc.setFontSize(10);
  decisions.forEach((decision) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    const color =
      decision.decision === 'receive' ? [0, 128, 0]
      : decision.decision === 'exclude' ? [255, 0, 0]
      : [200, 150, 0];
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(`[${decision.decision.toUpperCase()}] ${decision.user_id}`, 14, yPos);
    doc.setTextColor(0, 0, 0);
    yPos += 7;
    doc.text(`  Reason: ${decision.reason.substring(0, 70)}`, 18, yPos);
    yPos += 6;
    doc.text(`  Rules: ${decision.rule_sources.join(', ')}`, 18, yPos);
    yPos += 10;
  });
  doc.setFontSize(8);
  doc.text('Generated by Jikken', 14, 290);
  doc.save(`flag-simulation-${meta.flag_id}-${meta.simulation_id}.pdf`);
}

export function formatResultForClipboard(result: SimulationResult): string {
  let text = `FLAG SIMULATION REPORT\n`;
  text += `============================\n\n`;
  text += `Flag: ${result.flag_id}\n`;
  text += `Simulation ID: ${result.simulation_id}\n`;
  text += `Evaluated: ${result.evaluated_at}\n`;
  text += `Result: ${result.summary.passed} received, ${result.summary.conflicted} excluded, ${result.summary.warned} partial\n\n`;
  text += `Decisions:\n`;
  result.decisions.forEach((d) => {
    text += `  ${d.decision.toUpperCase()}: ${d.user_id}\n`;
    text += `    Reason: ${d.reason}\n\n`;
  });
  return text;
}